@startuml
class "<b>Persoon (schema:Person)</b>" {
    identifier : URI [1..1]
    alternatieve identifier : URI | ID [1..*]
    volledige naam : string [1..1]
    voornaam : string [0..*]
    achternaam : string [0..*]
    alias : string [0..*]
    geboortedatum : EDTF [0..*]
    sterfdatum : EDTF [0..*]
    externe identifier : URI [0..*]
}

class "<b>Plaats (schema:Place)</b>" {
    naam : string [1..1]
}

class "<b>Beroep (schema:Occupation)</b>" {
    naam : string [1..1]
}

class "<b>Afbeelding (schema:ImageObject)</b>" {
    identifier : URI [1..1]
    maker : string [1..1]
    licentie : URI [1..1]  
}

"<b>Persoon (schema:Person)</b>" "0" -> "*" "<b>Plaats (schema:Place)</b>" : geboorteplaats
"<b>Persoon (schema:Person)</b>" "0" -> "*" "<b>Plaats (schema:Place)</b>" : sterfplaats
"<b>Beroep (schema:Occupation)</b>" "*" <-- "0" "<b>Persoon (schema:Person)</b>": heeft beroep
"<b>Persoon (schema:Person)</b>" "0" --> "1" "<b>Afbeelding (schema:ImageObject)</b>": heeft afbeelding

class "<b>Organisatie (org:Organization)</b>" {
    naam : langString [1..1]
}

class "<b>Stelling (rdf:Statement)</b>"{
    eigenschap : URI [1..1]
    waarde : string | EDTF [1..1]
    gemaakt op: datum [1..1]
}
note bottom of "<b>Stelling (rdf:Statement)</b>"
    Mogelijke waarden voor "eigenschap":
    - alternatieve identifier
    - voornaam
    - achternaam
    - alias
    - geboortedatum
    - sterfdatum
    - geboorteplaats
    - sterfplaats
    - heeft beroep
    - heeft afbeelding
end note
 

"<b>Stelling (rdf:Statement)</b>" "1" -> "1" "<b>Persoon (schema:Person)</b>" : onderwerp
"<b>Stelling (rdf:Statement)</b>" "1" -> "1" "<b>Plaats (schema:Place)</b>" : waarde
"<b>Stelling (rdf:Statement)</b>" "1" -> "1" "<b>Beroep (schema:Occupation)</b>": waarde
"<b>Stelling (rdf:Statement)</b>" "1" -> "1" "<b>Afbeelding (schema:ImageObject)</b>": waarde
"<b>Stelling (rdf:Statement)</b>" "1" -u-> "1" "<b>Organisatie (org:Organization)</b>": bron

hide circle
hide methods
@enduml