@startuml
class "<b>Persoon (schema:Person)</b>" {
    heeft identifier : URI [1..1]
    volledige naam : string [1..1]
    voornaam : string [0..*]
    achternaam : string [0..*]
    alias : string [0..*]
    geboortedatum : EDTF [0..*]
    sterfdatum : EDTF [0..*]
    heeft externe identifier : URI [0..*]
    heeft bron : URI [0..*]
}

class "<b>Plaats (schema:Place)</b>" {
    naam : string [1..1]
}

class "<b>Beroep (schema:Occupation)</b>" {
    naam : string [1..1]
}

class "<b>Afbeelding (premis:file)</b>" {
    heeft identifier : URI [1..1]
}

"<b>Persoon (schema:Person)</b>" "0" -> "*" "<b>Plaats (schema:Place)</b>" : geboorteplaats [0..*]
"<b>Persoon (schema:Person)</b>" "0" -> "*" "<b>Plaats (schema:Place)</b>" : sterfplaats [0..*]
"<b>Beroep (schema:Occupation)</b>" "*" <-- "0" "<b>Persoon (schema:Person)</b>": heeft beroep [0..*]
"<b>Persoon (schema:Person)</b>" "0" --> "*" "<b>Afbeelding (premis:file)</b>": heeft afbeelding [0..*]
note on link: de omgekeerde relatie ook???


note bottom of "<b>Persoon (schema:Person)</b>": iedere property moet een bron hebben
note bottom of "<b>Afbeelding (premis:file)</b>"
    welke eigenschappen moet een afbeelding hebben?
    een contributor? 
    en is dit dan de organisatie of de persoon?
    technische metadata zoals in permis:file van KG?
end note

hide circle
hide methods
@enduml